# Generated by Django 5.1.3 on 2025-01-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='price',
        ),
        migrations.AddField(
            model_name='person',
            name='product',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
