# Generated by Django 5.1.3 on 2025-01-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
