# Generated by Django 5.1.3 on 2025-01-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_person_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Products',
        ),
    ]
