# Generated by Django 5.1.3 on 2025-01-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_person_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='Newlist',
        ),
    ]
