# Generated by Django 5.1.3 on 2025-01-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_list_newlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newlist',
            old_name='image',
            new_name='productname',
        ),
        migrations.RemoveField(
            model_name='newlist',
            name='product',
        ),
        migrations.AddField(
            model_name='newlist',
            name='newproduct',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
