# Generated by Django 5.1.3 on 2025-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_image_newlist_productname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuredproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('newproduct', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
