# Generated by Django 5.1.3 on 2025-01-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_rename_productname_featuredproducts_nameproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimg', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
