# Generated by Django 5.1.3 on 2025-02-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirmpass', models.CharField(max_length=30)),
            ],
        ),
    ]
