# Generated by Django 5.1.3 on 2025-02-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
