# Generated by Django 5.1.3 on 2025-02-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
