# Generated by Django 5.1.3 on 2025-02-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_products_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categori',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
