# Generated by Django 5.1.3 on 2025-02-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_products_categori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
