# Generated by Django 5.1.3 on 2025-02-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='More',
            new_name='Category',
        ),
    ]
