# Generated by Django 5.1.3 on 2025-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_more_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categori',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
