# Generated by Django 5.1.3 on 2025-02-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_category_categori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featuredproducts',
        ),
        migrations.DeleteModel(
            name='Newlist',
        ),
    ]
