# Generated by Django 5.1.3 on 2025-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_delete_featuredproducts_delete_newlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuredproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=30)),
                ('newimg', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Newlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newproduct', models.ImageField(upload_to='images/')),
                ('productname', models.CharField(max_length=30)),
            ],
        ),
    ]
