# Generated by Django 5.1.3 on 2025-02-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_featuredproducts_newlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.signup')),
            ],
        ),
    ]
