# Generated by Django 5.1.3 on 2025-02-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='userId',
        ),
    ]
