# Generated by Django 5.1.6 on 2025-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_rename_product_cart_productid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=1000)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PINCode', models.CharField(max_length=100)),
                ('PaymentMethod', models.CharField(max_length=100)),
            ],
        ),
    ]
