# Generated by Django 5.1.6 on 2025-03-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Fullname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='PINCode',
            new_name='pinCode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='state',
        ),
    ]
