# Generated by Django 5.1.6 on 2025-03-26 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_rename_address_order_address_rename_city_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='PaymentMethod',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pinCode',
            new_name='pincode',
        ),
    ]
