# Generated by Django 5.1.6 on 2025-03-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_rename_paymentmethod_order_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='paymentmethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
    ]
