# Generated by Django 5.1.6 on 2025-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_rename_paymentmethod_order_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(default='Cash on Delivery', max_length=100),
        ),
    ]
