# Generated by Django 5.1.6 on 2025-03-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_alter_order_fullname_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(max_length=100),
        ),
    ]
