# Generated by Django 5.1.6 on 2025-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_alter_order_fullname_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(default='Cash on Delivery', max_length=100),
        ),
    ]
