# Generated by Django 5.1.6 on 2025-04-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_alter_order_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
