# Generated by Django 5.1.6 on 2025-04-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='youremail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='yourname',
        ),
    ]
