# Generated by Django 5.1.6 on 2025-04-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0035_rename_email_contact_youremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='using',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
