# Generated by Django 5.1.6 on 2025-04-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_products_using'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproducts',
            name='forusing',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
