# Generated by Django 5.1.6 on 2025-04-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0037_featuredproducts_forusing'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlist',
            name='categori',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
